package com.github.manosbatsis.csvtxcompare.missmatches.repository;

import com.github.manosbatsis.csvtxcompare.missmatches.model.ClientMarkoffFile;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
 * Typical repository interface for {@link ClientMarkoffFile} entities.
 * Implementation is automatically generated by Spring
 * Created by manos on 12/9/2017.
 */
@Repository
public interface ClientMarkoffFileRepository
		extends JpaRepository<ClientMarkoffFile, String>,
		JpaSpecificationExecutor<ClientMarkoffFile> {
}
